### ISSUE TITLE
Glitches on Chromecast 4 with Android 12 on multiple streams, after updating Android from 10 to12

### ISSUE THREAD

**Issue by AGasztold** [google/ExoPlayer#10712]
### ExoPlayer Version

2.18.1

### Devices that reproduce the issue

Hello,
We have issued a lot of glitches on multiple streams from our CDN after updating Android (from 10 to 12) on Chromecast 4.
For example: 
https://r.dcs.redcdn.pl/dash/o2/portal/prod/vod/tears_of_steel/movie/dash/Manifest.ism
https://ls-proxy.redlabs.pl/license/wvpl?key=4328A83659094C4B79C8215075BF85D6
There was no problem with similar clear video: https://r.dcs.redcdn.pl/dash/o2/portal/prod/vod/tears_of_steel/trailer/dash/Manifest.ism
The problem is visible on Chromecast 4, Android 12 so far.
I will appreciate Your help.

### Devices that do not reproduce the issue

Other devices with lower Android version.

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Add to Exo playlist attached video source
2. Observe glitches

### Expected result

Media plays smoothly.

### Actual result

A lot of glitches are visible.

### Media

https://r.dcs.redcdn.pl/dash/o2/portal/prod/vod/tears_of_steel/movie/dash/Manifest.ism
https://ls-proxy.redlabs.pl/license/wvpl?key=4328A83659094C4B79C8215075BF85D6

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by christosts** [comment]
I can verify the glitches. The are batches for frames dropped, but they are not coming (or detected) from ExoPlayer. [vfpo](https://medium.com/google-exoplayer/improved-rendering-performance-operating-mediacodec-in-asynchronous-mode-and-asynchronous-buffer-3026207850b2) is high at arounf 44ms, so the player's rendering loop seems to be working fine. I think the frames are dropped by the components underneath the platform.

I will forward this to the Chromecast team - I assume I can share the content links and bug-report with the Chromecast team too

**Comment by AGasztold** [comment]
Please share the logs and content links with Chromecast team. Is it possible to have any feedback from further investigation in this thread?

**Comment by christosts** [comment]
> Is it possible to have any feedback from further investigation in this thread?
Yes

**Comment by christosts** [comment]
[internal ref 254842727]

**Comment by AGasztold** [comment]
Hi, do you have any feedback from this issue? Maybe is it something specific related to our streams?

**Comment by christosts** [comment]
The Chromecast team has verified the problem and is working on a fix. I don't have any news on when the fix will be completed or rolled out to devices.

**Comment by AGasztold** [comment]
Hi, thank you for the feedback. Does Chromecast team have any details about that fix? Did they notice something specific in our streams which is problematic? From our side: we have noticed that we are seeing glitches on streams encoded with nvenc (h264).

**Comment by christosts** [comment]
I'm afraid the team did not mention anything about the specific stream, all I know is that it is fixed.

**Comment by AGasztold** [comment]
Hi, do you know approximate date of the rollout of this fix? I will appreciate the answer.

**Comment by christosts** [comment]
I'm afraid I don't have that information.

**Comment by AGasztold** [comment]
Is it possible to test this fix before rollout? We could pass serial number of our device if needed. I will appreciate your help.

**Comment by tominkozhimala** [comment]
Has there been any update from the Chromecast team on the rollout of this fix? Issue still persists

**Comment by christosts** [comment]
Apologies for the silence, the team will start rolling out the fix next week gradually, the target is to have the update sent to all devices by end of March 2023.

**Comment by AGasztold** [comment]
Hello, is there any update regarding rollout?

**Comment by christosts** [comment]
Sorry for the delay, I believe the release is planned for this month.
