### ISSUE TITLE
Cannot passthrough dolby ac3 to receive

### ISSUE THREAD

**Issue by quanghuy1288** [google/ExoPlayer#2816]
I have tried Exo player with Dolby AC3 by HLS streaming (link is http://123.30.233.143/vod/a.mp4/playlist.m3u8 )

My device is an android box (version 5.1). That box connect with a dolby audio receive via HDMI. But it always show error log 
[ac3.txt](https://github.com/google/ExoPlayer/files/995079/ac3.txt)

(with default player of my android box, it can downrate ac3 to stereo PCM)

**Comment by andrewlewis** [comment]
Please attach a full bug report (`adb bugreport`) as requested.

**Comment by quanghuy1288** [comment]
I have attached bugreport.
[ac3debug.txt](https://github.com/google/ExoPlayer/files/995307/ac3debug.txt)

**Comment by andrewlewis** [comment]
This is probably a device specific issue that needs to be followed up with the device OEM.

You mention that the default player on the device can decode AC-3. If you pass `null` AudioCapabilities when constructing the audio renderer, you will likely get the same behavior.

**Comment by quanghuy1288** [comment]
If my android box passthrough to receiver: it must play ok
If my android decode ac-3 like defaul build in player, it must play ok. Why defaul build in player play ok but Exoplayer is failed?

**Comment by andrewlewis** [comment]
Yes: if the device has HDMI passthrough mode implemented correctly and you attach it to a receiver that supports AC-3, it should work. However, it's clear from the bug report that the AudioTrack is failing to initialize. You could try to debug this a bit yourself by verifying that the AudioTrack is being configured for [ENCODING_AC3](https://developer.android.com/reference/android/media/AudioFormat.html#ENCODING_AC3) and seeing if any other AC-3 streams play on the same device. Beyond that, I suggest asking the device manufacturer to investigate. HDMI passthrough from ExoPlayer works on other devices.

Did you try passing `null` as the AudioCapabilities when constructing the audio renderer, as I suggested above? This will cause the device's AC-3 decoder (if present) to be used even if the HDMI connection is advertising support for passthrough.

I'll close this for now as there's nothing actionable for us to do. Please reopen if you can determine that this is a bug in ExoPlayer. Thanks!

**Comment by quanghuy1288** [comment]
Hi,

I have debug our Android box (check attached test.zip). It show: 
- "05-29 16:51:50.655 10473 10473 W hbabyyyyyyyyyyyyyyyyyyy: AudioTrack:audioCapabilities AudioCapabilities[maxChannelCount=8, supportedEncodings=[2, 5, 6]]" ==> Is this mean it support AC3 encoding?
- "05-29 16:51:51.152 10473 10549 W AudioCapabilities: Unsupported mime audio/ac3" 
- "05-29 16:51:51.172 10473 10549 D MediaCodecInfo: NoSupport [channelCount.support, 6] [AML.google.ac3.decoder, audio/ac3] [p201, IV3012A7, amlogic, 22]"
I do not conect box with receiver, so it use default decoder of Android box. Box do not play.
When debug with my samsung note3 - which have no ac3 decoder too, my note3 play with no sound. What make different between my Android box and my note3?

**Comment by quanghuy1288** [comment]
up debug log of my Android box and my note3
[android_box.txt](https://github.com/google/ExoPlayer/files/1035536/android_box.txt)
[note3.txt](https://github.com/google/ExoPlayer/files/1035535/note3.txt)

**Comment by quanghuy1288** [comment]
I can not reopen this issue. Do you see my comment @andrewlewis  ?

**Comment by andrewlewis** [comment]
`supportedEncodings=[2, 5, 6]` indicates that the audio track can output 16-bit PCM and AC-3/E-AC-3 via passthrough.

`MediaCodecInfo: NoSupport [channelCount.support, 6] [AML.google.ac3.decoder, audio/ac3] [p201, IV3012A7, amlogic, 22]` indicates that the device has an AC-3 decoder but it doesn't declare support for decoding 6 channel input. This could either be an actual limitation of the decoder, or the decoder could be under-reporting its capabilities. You could try modifying MediaCodecInfo to return `true` from `isAudioChannelCountSupportedV21` to try using the decoder anyway, and see if it works.

**Comment by quanghuy1288** [comment]
I have tried your guide, always return true but player still can not work.

I have check with OEM, they said that device decode dolby by software. And i have tried other dolby file: 2 channels, 44100Hz ac3, but player still error: http://103.216.120.24/vod51/ac3.4.mp4/playlist.m3u8 

You can check log debug: "06-01 14:52:57.634  8300  8300 D EventLogger:       [X] Track:0, id=1/129, mimeType=audio/ac3, channels=2, sample_rate=44100, supported=NO_EXCEEDS_CAPABILITIES" 
[test.logse1d.txt](https://github.com/google/ExoPlayer/files/1044029/test.logse1d.txt)

**Comment by andrewlewis** [comment]
Based on the logging you pasted, the stereo 44.1 kHz format exceeds the advertised decoder capabilities Can you follow up with the OEM regarding whether the decoder actually supports this format? If so, it is underreporting the capabilities and they should fix it.

If you change the code to return `true` from `isAudioChannelCountSupportedV21` and `isAudioSampleRateSupportedV21`, but playback still didn't work, I think you would have seen a different error. What is the error in that case?

**Comment by quanghuy1288** [comment]
[log.3.txt](https://github.com/google/ExoPlayer/files/1044179/log.3.txt)

If you change the code to return true from isAudioChannelCountSupportedV21 and isAudioSampleRateSupportedV21, but playback still didn't work, I think you would have seen a different error.  ==> still show simillar error. Please check attached log

**Comment by quanghuy1288** [comment]
Player show: Unable to instantiate decoder AML.google.ac3.decoder

**Comment by andrewlewis** [comment]
From the log: `E OMXNodeInstance: setParameter(3e:AML.google.ac3.decoder, ParamAudioPcm(0x4000002)) ERROR: UnsupportedIndex(0x8000101a)` `E ACodec  : [AML.google.ac3.decoder] configureCodec returning error -1010`.

Please follow up with the OEM to find out why `MediaCodec.configure` is throwing when provided with a stereo 44.1 kHz format. It is not surprising that an error is thrown, given that this exceeds the advertised codec capabilities, but if they support AC-3 it seems like they should support this input format.

**Comment by quanghuy1288** [comment]
Hi, 

I have checked our OEM. They have talked with Amlogic vendor, Amlogic used Amlogic 's private player to decode Dolby.
How to config to passthrough audio?

**Comment by andrewlewis** [comment]
To use passthrough mode, you just an AudioCapabilities instance when constructing MediaCodecAudioRenderer, as we do in [DefaultRenderersBuilder](https://github.com/google/ExoPlayer/blob/1e12c07/library/core/src/main/java/com/google/android/exoplayer2/DefaultRenderersFactory.java#L219). Then passthrough will be used automatically if it's supported by the connected device. As I noted above, based on the AudioCapabilities logging you pasted AC-3 passthrough should work on this device, and you'll need to follow up with the OEM if it doesn't.

**Comment by quanghuy1288** [comment]
Do you have any way to alway active passthrough audio and disable build in decoder of device?

**Comment by andrewlewis** [comment]
Passthrough will be used automatically if it's available. #2148 has some more information on this.

To disable using the built-in decoder you could provide your own MediaCodecSelector implementation that returns `null` when asked for an AC-3 decoder on this device.

**Comment by quanghuy1288** [comment]
Hi,

I have tried to test my android box with other TV (TV without ac3 decoder) and i see in the debug log show that: "AudioTrack:audioCapabilities AudioCapabilities[maxChannelCount=2, supportedEncodings=[2]]"
So it mean: box has no ability to decode ac3 audio.

So i think problem of pass through audio is caused of Exo player.
[6.5.log.txt](https://github.com/google/ExoPlayer/files/1051817/6.5.log.txt)

**Comment by andrewlewis** [comment]
`supportedEncodings=[2]` indicates that only 16-bit PCM can be output over the HDMI connection, not AC-3. It doesn't relate to on-device decoding.

Based on your comments above, the AudioTrack can't be initialized for passthrough output when connected to an A/V receiver, and the on-board AC-3 decoder doesn't support the format. You'd need to follow up with the OEM to address these issues. I can't really give any more assistance here.

**Comment by quanghuy1288** [comment]
Hi,
"supportedEncodings=[2] indicates that only 16-bit PCM can be output over the HDMI connection, not AC-3. It doesn't relate to on-device decoding."  ==> Infact, i disconnect HDMI from TV.

**Comment by ojw28** [comment]
As mentioned repeatedly above, you need to get the OEM to assist with this issue.

**Comment by quanghuy1288** [comment]
Hi,
I am work with OEM about this issue. But i need know exactly the problem.
1/ when i disconnect HDMI of my Android box, log show: "supportedEncodings=[2]". Does it mean supportedEncodings of the box?
2/ when i connect HDMI of of my Android box to a LG smartTV, log show: "supportedEncodings=[2, 5, 6]". Does it mean supportedEncodings  of the box or the smartTV?

**Comment by andrewlewis** [comment]
Your questions are basically answered already above: `supportedEncodings=[2, 5, 6]` indicates that the audio track can output 16-bit PCM and AC-3/E-AC-3 via passthrough, and `supportedEncodings=[2]` indicates that only 16-bit PCM can be output (which is expected if no A/V receiver is attached).

Note that AudioCapabilities tell the player what formats can be output via passthrough, and are unrelated to whether the device can decode AC-3 (for example).
