### ISSUE TITLE
LoadEventInfo.dataSpec is null on call from EventListener.onLoadStarted (AnalyticsListener.onLoadStarted)

### ISSUE THREAD

**Issue by arazabishov** [google/ExoPlayer#4715]
### Issue description
`AnalyticsListener.onLoadStarted()` is called with an `LoadEventInfo` object with null `dataSpec`. It seems that issue is specific to audio only media source types. The expected behavior is to receive `dataSpec` for all media source types. Please note, I get the same results when adding `EventListener` to the player.

### Reproduction steps
This issue is reproducible in the demo app. You need to update `EventLogger.onLoadStarted()` to print `LoadEventInfo.dataSpec` value.

```java
  @Override
  public void onLoadStarted(EventTime eventTime, LoadEventInfo loadEventInfo, MediaLoadData mediaLoadData) {
    logd(eventTime, "onLoadStarted() -> " + loadEventInfo.dataSpec);
  }
```

### Link to test content
Try playing content from the demo app - Misc - Google Play (MP3 Audio), Google Play (Ogg / Vorbis Audio), Apple AAC 10s, etc. For all of those audio tracks, dataSpec is going to be null. dataSpec is present in the demo app for HLS for instance.

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
Tested on android emulator with API level 26, 27. Tested on Google Pixel XL running API 28 as well.

**Comment by tonihei** [comment]
That has been fixed over 2 months ago in our dev branch. Not sure how it not ended up in a release yet :) 

It will hopefully be included in the upcoming 2.9.0 release.

**Comment by arazabishov** [comment]
Thanks for the quick response @tonihei. Do you have an idea when 2.9.0 will be released? :)

**Comment by tonihei** [comment]
Probably soon. But we don't have a fixed date yet, sorry.

**Comment by arazabishov** [comment]
I understand, thanks guys!

**Comment by kgrevehagen** [comment]
Hi @tonihei, now that 2.9.0 is out, I still see some issues with this. Could you link the commit that fixed this, just out of curiosity?

What I am seeing is that windowIndex is always 0, even though it fetches the next item in the ConcatenatingMediaSource(prefetching next item while playing current). Also, dataSpec is no longer null, but pretty much empty:
`DataSpec[GET , null, 0, 0, -1, null, 0]`
The uri in the dataspec might be expected to be null in my case in onLoadStarted, since we set it inside the DataSource, but it is also null in onLoadCompleted.

I'll be happy to help any more if that is wanted.
Thanks in advance!

**Comment by kgrevehagen** [comment]
Turns out the `windowIndex` issue was my fault after all. When using `ConcatenatingMediaSource`, the `MediaSourceEventListener` needs to be added to that, and not each `MediaSource` inside it.
Am I correct in assuming this behaviour? Might just be me, but this could maybe be improved somehow in the documentation?

**Comment by tonihei** [comment]
Yes, that's correct. You may also try to use `AnalyticsListener` which can be added to `SimpleExoPlayer` and gives you the load events together with window index and timeline information for more context.
