### ISSUE TITLE
Calling ExoPlayer.next() leads to new audio session ID every time

### ISSUE THREAD

**Issue by davidaik** [google/ExoPlayer#5302]
I'm using `SimpleExoPlayer` and `ConcatenatingMediaSource` in my app.

Calling `next()` at any time on the ExoPlayer instance leads to a new audio session being generated and my attached equalizer and other audio effects are not working any more. I could work around this by re-initializing my equalizer every time the audio session id changes, but I don't think a new audio session ID should be generated in the first place.

I found that new audio session id is not generated if the currently playing song completes and it automatically switches to the next song in the `ConcatenatingMediaSource`. The "bug" occurs only when I call `next()`.

Tested on multiple devices and emulators. Android 5.1 to 9.

Re-initializing the equalizer every time on audio session id change is making the next song start playing with normal equalizer settings for a fraction of a second. Really unpleasant effect.

**Comment by davidaik** [comment]
To confirm that a call to `next()` was indeed causing a new audio session id to be generated, I tested using the following code.

`private Runnable testRunnable = new Runnable() {`
    `@Override`
        `public void run() {`
            `if(mExoPlayer.hasNext())`
                  `mExoPlayer.next();`
        `}`
`};`


And somewhere,
    `mHandler.postDelayed(testRunnable, 5000);`

**Comment by tonihei** [comment]
That happens because the decoders are reset when calling next(). We already implemented a change which should prevent this from happening. @ojw28 may be able to comment further.

**Comment by ojw28** [comment]
Yes, I think this is probably fixed already in the `dev-v2` branch. Please give it a try and let us know if it's working there.

Note:  You should still handle the audio session ID changing in application code, since I think there are probably edge cases where this can still occur.

**Comment by DKillWorld** [comment]
I will check if its working in next release. Inform here once updated.

**Comment by davidaik** [comment]
Hmm I'll try and test this soon. Just to be clear, would the fix be included in the next release?

**Comment by ojw28** [comment]
It will be included in `2.10.0` (this is probably not the next release; there are likely further `2.9.x` releases prior to that).
