### ISSUE TITLE
SimpleExoPlayer GestureDetector.OnGestureListener scroll events triggered on taps

### ISSUE THREAD

**Issue by T-10001** [google/ExoPlayer#5725]
### [REQUIRED] Issue description
When setting the PlayerView with setPlayer and the player is a SimpleExoPlayer, just tapping the screen causes an [GestureDetector.OnGestureListener](https://developer.android.com/reference/android/view/GestureDetector.OnGestureListener) trigger a [scrolling event](https://developer.android.com/reference/android/view/GestureDetector.OnGestureListener.html#onScroll(android.view.MotionEvent,%20android.view.MotionEvent,%20float,%20float)). 
In addition, the tap event onDown() is ignored.

Without the SimpleExoPlayer set as the player, the tap does not trigger a scrolling event, but an onDown() tap event.

I tried to add same gesturing code to ExoPlayer demo app, but was getting "Cannot resolve symbol 'GestureDetectorCompat' error and couldn't even import the class.

### [REQUIRED] Reproduction steps
1. Get code from the repository https://github.com/s3433557/SwipeTester and run
2. Tap anywhere on screen with app running
3. observe the number value display changing. It should only change when a scroll occurs, but a tap changes the value as well because the tap is registered as a scroll not a tap.
4. Comment out the line 82 "playerView.setPlayer(player);" of file MainActivity and run the new app.
5. Observe the value does not change when tapping the screen, only when scrolling the screen.

### [REQUIRED] Link to test content
No media required to reproduce issue.

### [REQUIRED] A full bug report captured from the device
[bugreport.zip](https://github.com/google/ExoPlayer/files/3041455/bugreport.zip)

### [REQUIRED] Version of ExoPlayer being used
Exoplayer versions used:
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.8.1'
    implementation 'com.google.android.exoplayer:exoplayer-core:2.9.1'
    implementation 'com.google.android.exoplayer:exoplayer-dash:2.9.1'

### [REQUIRED] Device(s) and version(s) of Android being used
Occurs on:
- Samsung Galaxy S8 9.0 and 8.1
- UmiDigi C Note 2 7.0
- Samsung Galaxy Tab A 8.1

Triggers tap as normal on: 
- HTC One M8 6.0 although playback controls don't appear so possibly the SimpleExoPlayer failed to be applied.

**Comment by andrewlewis** [comment]
`PlayerView` can intercept the `ACTION_DOWN` motion event in the case where there are player controls, because it returns `true` from `onTouchEvent` if it toggled controller visibility. I think what's going on is that the gesture detector never sees that event but it does see other touch events that are not handled by this child view, which it interprets as a scroll.

I'm not sure whether we should change this behavior because we are indeed intercepting the touch event. Could you describe the behavior you're looking for? I think one option would be to subclass `PlayerView` and override `onTouchEvent` to return `false` always. Then you'll get the controller toggling behavior but also handle scrolling as part of the same gesture. Or if you just set `use_controller` to `false` so controls are always hidden I think that would also 'fix' this.

Side note: the reason the HTC One device behaves differently is probably that the test app is not initializing the player on API 23.

**Comment by T-10001** [comment]
> Could you describe the behavior you're looking for? 

I was trying to implement scrolling/swiping vertically for volume control and horizontally for seeking like in various other players. Not sure if other players use the `GestureDetector.OnGestureListener`, but it is a problem if just tapping the screen causes video to seek or volume to change.

When tapping, I would like just the controls toggle visibility like usual.

> I think one option would be to subclass PlayerView and override onTouchEvent to return false always. Then you'll get the controller toggling behavior but also handle scrolling as part of the same gesture.

I tried subclassing `PlayerView` and return `false` for `onTouchEvent` always (as described by you) but that only causes controls to always be visible and seems to ignore any other gestures.

**Comment by ojw28** [comment]
@tonihei - Is it possible your recent changes to `PlayerView` touch handling fixed this?

**Comment by tonihei** [comment]
Yes, I think that should be fixed because we no longer intercept TOUCH_DOWN events but use the standard click handling detection instead. See #5784.

**Comment by T-10001** [comment]
@tonihei @ojw28 
I subclassed `PlayerView` and overrid `onTouchEvent` with the changes in the [21b2a47](https://github.com/google/ExoPlayer/commit/21b2a471bb1580ef5e0d1ae5584a25dc8ca9d683) commit, namely:

```
@Override
  public boolean onTouchEvent(MotionEvent event) {
    switch (event.getAction()) {
      case MotionEvent.ACTION_DOWN:
        isTouching = true;
        return true;
      case MotionEvent.ACTION_UP:
        if (isTouching) {
          isTouching = false;
          performClick();
          return true;
        }
        return false;
      default:
        return false;
    }
  }
```
Using the subclass, the problematic tap/scrolling behaviour is still the same.
Please see updated project https://github.com/s3433557/SwipeTester

**Comment by tonihei** [comment]
Thanks for doing the verification! We'll need to take another look then.

**Comment by tonihei** [comment]
I investigated this problem a bit and I think it's working as expected.

Each touch event gets forwarded to the lowest-level `View` first. That means `PlayerView` gets the first chance to handle a touch event before the `Activity` gets the event. Because `PlayerView `does indeed handle the touch event (for DOWN and UP), it returns true from `onTouchEvent`. That also means that elements higher up in the hierarchy never get the touch event at all. Only the MOVE events end up in `Activity.onTouchEvent` and that's why you are seeing scrolls only as the `GestureDetector` never got anything besides MOVE events.

If you want to add your custom touch handling to the `PlayerView` (or any other `View` for that matter), you should set an `OnTouchListener` which gets called before the view's `onTouchEvent` and thus can read and/or intercept all events:
```
playerView.setOnTouchListener((view, event) -> {
    gestureDetectorCompat.onTouchEvent(event);
    return false;
  });
```
Forwarding the events to the `GestureDetectorCompat` in `OnTouchListener` ensures you get all events and that the gestures are detected correctly. The return value of `OnTouchListener.onTouch` then decides whether `PlayerView` is allowed to handle the touch as well. If you return `true`, `PlayerView` never gets the touch and you can effectively not tap to show or hide the controls. If you return `false`, `PlayerView` still gets the events and the show/hide mechanism is working too.
